### ISSUE TITLE
CLOUD Wiki: Need information on how we are carbon neutral

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_cloud#12]
I'm adding language to the website about how we are a carbon neutral peer-to-peer cloud. So we need to back that up on the cloud wiki somewhere.

- [x] Kristof wiki page on how carbon neutral (@despiegk @Sacha96)
- [x] Add button on website linking there (@Vilnite)

**Comment by samtaggart** [comment]
@despiegk Can you please confirm if/when this should be done? For now I am putting into "now."

Also I cannot put it in the wiki project, maybe I don't have the appropriate rights.

**Comment by samtaggart** [comment]
@Sacha96 Since you are owning wikis I am adding you here as well. Let's figure out a solution while we are all three in Egypt.

**Comment by Sacha96** [comment]
@despiegk as per our conversation around TAG and how the carbon credits work, please confirm if the following is ok:
- 10% of fees to users of the grid will cover the carbon footprint of the grid. 
- These fees will be re-allocated to projects like TAG in the form of carbon credits.
- Carbon credits will finance planet positive projects lead by students (ex: planting tress, apparently TAG planted 60M trees).
- A reporting from TAG will provide transparency across these practices and will be part of yearly reports from the foundation's impact activities.

If we can get further details here, even in bullet points I could get started on a wiki page. Thanks

**Comment by Sacha96** [comment]
ThreeFold: Enabling the first Carbon Neutral P2P Cloud in the world. 

Despite public clouds announcing carbon neutrality, it is important to realise that most of the current strategies surround the monopolisation of green energy supplies to power their hyper-scale data centres. While some may say this is sustainable, it actually reduces the amount of green energy available to the rest of the economies they operate in. The only real way of achieving carbon neutrality, is to bring renewable energy in-house and to compensate for the energy used in the form offsets. 

How ThreeFold will achieve that milestone

- Collaborating with partners to create a collaborative carbon neutral P2P Cloud. 
- Using Zero-OS - the most energy efficient operating system to run P2P Cloud workloads, enabling +90% energy savings.
- Looking at sustainable node alternatives that have the following features: 
    - Liquid and/or immersion cooling (to reduce cooling energy consumption)
    - Can be easily combined with renewable energy sources
    - Tamper proof (for security)
    - Cost effective (to be plugged-in anywhere).
- ThreeFold engages itself to maximise the use of solar energy and other forms of renewable energies according to natural conditions (Ex: Wind energy where there is much wind) 
- As part of the sales price of the P2P Cloud, a portion will be allocated to compensate for the carbon emissions of the ThreeFold Grid, and converted into carbon credits.
- The carbon credits will be re-invested in projects such as TAG where 2,5+ million students from all around the world collaborative on planet positive projects to fight climate change.

What is a carbon offset?

A carbon offset is a reduction in emissions of carbon dioxide or other greenhouse gases made in order to compensate for emissions made elsewhere. Offsets are measured in tonnes of carbon dioxide-equivalent. One tonne of carbon offset represents the reduction of one tonne of carbon dioxide or its equivalent in other greenhouse gases

What is a carbon credit?

A carbon credit is a generic term for any tradable certificate or permit representing the right to emit one tonne of carbon dioxide or the equivalent amount of a different greenhouse gas. Carbon credits and carbon markets are a component of national and international attempts to mitigate the growth in concentrations of greenhouse gases.

**Comment by Sacha96** [comment]
https://github.com/threefoldfoundation/info_cloud/commit/05586d0901d98b754d740b2f8a09c19ea72dd212 see file

**Comment by Sacha96** [comment]
@despiegk ready for review
